services:
  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg17
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw
      - ./postgres/userfile:/etc/userfile:ro
    networks:
      - rsbp-internal

  web:
    container_name: web
    build: ./web
    env_file:
      - .env
    # ports:
    #   - 8000:80
    expose:
      - 80
    depends_on:
      - postgres
    networks:
      - rsbp-internal
      - rsbp-net

networks:
  rsbp-internal:
  rsbp-net:
    driver: bridge